SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

# Game area dimensions (play area)
GAME_AREA_WIDTH = 800
GAME_AREA_HEIGHT = 600


ENEMY_SIZE = 10
BULLET_SIZE = 8

URANEK_FRAME_WIDTH  = 200
URANEK_FRAME_HEIGHT = 200
skale = 0.7
URANEK_SIZE = (URANEK_FRAME_WIDTH * skale, URANEK_FRAME_HEIGHT * skale)

